"""Shared External Intelligence & Evidence Fabric enums."""

from __future__ import annotations

from enum import StrEnum


class RadarName(StrEnum):
    OPEN_WEB_RADAR = "OPEN_WEB_RADAR"
    X_RADAR = "X_RADAR"
    NEWS_RADAR = "NEWS_RADAR"
    REDDIT_RADAR = "REDDIT_RADAR"
    TELEGRAM_RADAR = "TELEGRAM_RADAR"
    GITHUB_RADAR = "GITHUB_RADAR"
    SECURITY_RADAR = "SECURITY_RADAR"
    REGULATORY_RADAR = "REGULATORY_RADAR"


class MissionName(StrEnum):
    TECHNOLOGY_DEVELOPMENT = "TECHNOLOGY_DEVELOPMENT"
    BINANCE_OPPORTUNITY_NEWS = "BINANCE_OPPORTUNITY_NEWS"
    SECURITY_RISK = "SECURITY_RISK"
    REGULATORY_RISK = "REGULATORY_RISK"
    MARKET_NARRATIVE = "MARKET_NARRATIVE"
    SOURCE_CREDIBILITY = "SOURCE_CREDIBILITY"
    EVIDENCE_VERIFICATION = "EVIDENCE_VERIFICATION"


class SourceType(StrEnum):
    WEB_ARTICLE = "WEB_ARTICLE"
    OFFICIAL_DOCUMENT = "OFFICIAL_DOCUMENT"
    RESEARCH_PAPER = "RESEARCH_PAPER"
    RSS_ENTRY = "RSS_ENTRY"
    X_POST = "X_POST"
    NEWS_ARTICLE = "NEWS_ARTICLE"
    REDDIT_POST = "REDDIT_POST"
    TELEGRAM_MESSAGE = "TELEGRAM_MESSAGE"
    GITHUB_REPOSITORY = "GITHUB_REPOSITORY"
    SECURITY_ADVISORY = "SECURITY_ADVISORY"
    REGULATORY_NOTICE = "REGULATORY_NOTICE"
    UNAVAILABLE = "UNAVAILABLE"


class VerificationStatus(StrEnum):
    VERIFIED = "VERIFIED"
    PARTIALLY_VERIFIED = "PARTIALLY_VERIFIED"
    UNVERIFIED = "UNVERIFIED"
    CONFLICTING = "CONFLICTING"
    FALSE = "FALSE"
    STALE = "STALE"
    MISLEADING = "MISLEADING"
    DATA_UNAVAILABLE = "DATA_UNAVAILABLE"


class DecisionImpact(StrEnum):
    CONFIRM = "CONFIRM"
    WEAK_CONFIRM = "WEAK_CONFIRM"
    NEUTRAL = "NEUTRAL"
    CONFLICT = "CONFLICT"
    RISK = "RISK"
    CRITICAL_RISK = "CRITICAL_RISK"
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
    DATA_UNAVAILABLE = "DATA_UNAVAILABLE"
    MANUAL_REVIEW_REQUIRED = "MANUAL_REVIEW_REQUIRED"
    NO_TRADE_RECOMMENDED = "NO_TRADE_RECOMMENDED"


class AssetClass(StrEnum):
    ELIGIBLE_COIN = "ELIGIBLE_COIN"
    STABLECOIN = "STABLECOIN"
    WRAPPED_ASSET = "WRAPPED_ASSET"
    LEVERAGED_ASSET = "LEVERAGED_ASSET"
    INDEX_ASSET = "INDEX_ASSET"
    UNKNOWN = "UNKNOWN"
    EXCLUDED = "EXCLUDED"


class RadarStatus(StrEnum):
    READY = "READY"
    DEGRADED = "DEGRADED"
    DATA_UNAVAILABLE = "DATA_UNAVAILABLE"


class ProviderOperationalState(StrEnum):
    AVAILABLE = "AVAILABLE"
    DEGRADED = "DEGRADED"
    RATE_LIMITED = "RATE_LIMITED"
    BUDGET_LIMITED = "BUDGET_LIMITED"
    AUTH_ERROR = "AUTH_ERROR"
    UNAVAILABLE = "UNAVAILABLE"
    SOURCE_NOT_REQUIRED = "SOURCE_NOT_REQUIRED"


class RetrievalStatus(StrEnum):
    VALID = "VALID"
    PARTIAL = "PARTIAL"
    STALE = "STALE"
    INCONSISTENT = "INCONSISTENT"
    CORRUPTED = "CORRUPTED"
    DATA_UNAVAILABLE = "DATA_UNAVAILABLE"
    SOURCE_NOT_REQUIRED = "SOURCE_NOT_REQUIRED"


class ExtractionMethod(StrEnum):
    DETERMINISTIC = "DETERMINISTIC"
    LOCAL_LLM = "LOCAL_LLM"


class TechnologyRecommendation(StrEnum):
    WATCH = "WATCH"
    RESEARCH_CANDIDATE = "RESEARCH_CANDIDATE"
    PROTOTYPE_CANDIDATE = "PROTOTYPE_CANDIDATE"
    BACKLOG = "BACKLOG"
    REJECT = "REJECT"
    DATA_UNAVAILABLE = "DATA_UNAVAILABLE"


class OpportunityStatus(StrEnum):
    OPPORTUNITY_CANDIDATE = "OPPORTUNITY_CANDIDATE"
    WATCH = "WATCH"
    REQUIRES_TECHNICAL_CONFIRMATION = "REQUIRES_TECHNICAL_CONFIRMATION"
    REQUIRES_LIQUIDITY_CONFIRMATION = "REQUIRES_LIQUIDITY_CONFIRMATION"
    REQUIRES_RISK_VALIDATION = "REQUIRES_RISK_VALIDATION"
    DATA_UNAVAILABLE = "DATA_UNAVAILABLE"
