"""Universal governed-object enforcement contracts and fail-closed engine."""

from ai4binance.governance.enforcement.adapters import (
    envelope_from_execution_authority_profile,
    envelope_from_governed_knowledge,
    envelope_from_policy_document,
    envelope_from_repository_artifact,
    envelope_from_tool_policy_document,
)
from ai4binance.governance.enforcement.contracts import (
    EnforcementControlResult,
    EnforcementDecision,
    EnforcementGate,
    EnforcementOutcome,
    EnforcementProfile,
    EnforcementRequest,
    GovernedObjectEnvelope,
)
from ai4binance.governance.enforcement.engine import (
    CONSEQENTIAL_ACTIONS,
    DeterministicEnforcementEngine,
)
from ai4binance.governance.enforcement.inventory import (
    DEFAULT_ENFORCEMENT_INVENTORY_PATH,
    EnforcementCoverageState,
    EnforcementInventory,
    EnforcementInventoryEntry,
    RequirementAssuranceChain,
    RequirementAssuranceDecision,
    RequirementTraceabilityEntry,
    RequirementTraceabilityInvariants,
    RequirementTraceabilityRegistry,
    RequirementTraceStatus,
    consequential_entrypoint_ids,
    inventory_actions_for_object_type,
    inventory_entrypoint_ids,
    inventory_object_types,
    inventory_scope_families,
    load_enforcement_inventory,
    required_scope_families,
    routed_or_explicitly_blocked_entrypoint_ids,
    uncovered_consequential_entrypoint_ids,
)
from ai4binance.governance.enforcement.receipt import (
    PolicyEnforcementReceipt,
    PolicyEnforcementStatus,
    build_policy_enforcement_receipt,
)
from ai4binance.governance.enforcement.registry import (
    DEFAULT_ENFORCEMENT_PROFILE_REGISTRY_PATH,
    EnforcementProfileRegistry,
    expected_governed_object_types,
    load_enforcement_profile_registry,
)

__all__ = [
    "CONSEQENTIAL_ACTIONS",
    "DEFAULT_ENFORCEMENT_INVENTORY_PATH",
    "DEFAULT_ENFORCEMENT_PROFILE_REGISTRY_PATH",
    "DeterministicEnforcementEngine",
    "EnforcementControlResult",
    "EnforcementCoverageState",
    "EnforcementDecision",
    "EnforcementGate",
    "EnforcementInventory",
    "EnforcementInventoryEntry",
    "EnforcementOutcome",
    "EnforcementProfile",
    "EnforcementProfileRegistry",
    "EnforcementRequest",
    "GovernedObjectEnvelope",
    "PolicyEnforcementReceipt",
    "PolicyEnforcementStatus",
    "RequirementAssuranceChain",
    "RequirementAssuranceDecision",
    "RequirementTraceStatus",
    "RequirementTraceabilityEntry",
    "RequirementTraceabilityInvariants",
    "RequirementTraceabilityRegistry",
    "build_policy_enforcement_receipt",
    "consequential_entrypoint_ids",
    "envelope_from_execution_authority_profile",
    "envelope_from_governed_knowledge",
    "envelope_from_policy_document",
    "envelope_from_repository_artifact",
    "envelope_from_tool_policy_document",
    "expected_governed_object_types",
    "inventory_actions_for_object_type",
    "inventory_entrypoint_ids",
    "inventory_object_types",
    "inventory_scope_families",
    "load_enforcement_inventory",
    "load_enforcement_profile_registry",
    "required_scope_families",
    "routed_or_explicitly_blocked_entrypoint_ids",
    "uncovered_consequential_entrypoint_ids",
]
