"""LLMOps metadata and observe-only Codex model-governance contracts."""

from ai4binance.multiops.contracts import OpsCapability, OpsDomain
from ai4binance.multiops.llmops.contracts import (
    BudgetStatus,
    ModelTier,
    ModelUsageRecord,
    ReasoningEffort,
    TaskClass,
    TaskCriticality,
    TokenAccountingSource,
)
from ai4binance.multiops.llmops.policy import (
    BaselineManifest,
    BaselineTaskDefinition,
    BudgetLimit,
    EnforcementMode,
    ModelAuthorityCeiling,
    ModelCandidate,
    ModelCandidatePolicy,
    ModelCapabilityEvidence,
    ModelContextRequirement,
    ModelGovernancePolicy,
    ModelInvocationEvidence,
    ModelRoutingCapability,
    ModelSelectionDecision,
    ModelSelectionGateway,
    ModelSelectionOutcome,
    ModelSelectionRequest,
    PricingSource,
    ProviderRoutingStatus,
    SelectionResourceBudget,
    StructuredOutputRequirement,
    TaskRoutingProfile,
    load_baseline_manifest,
    load_model_governance_policy,
    route_model_selection_request,
    select_model_candidate,
)
from ai4binance.multiops.llmops.usage import (
    ModelUsageLedger,
    default_model_usage_path,
    unavailable_usage_record,
)

DOMAIN = OpsDomain.LLMOPS
CAPABILITIES = (
    OpsCapability.PROMPT_REGISTRY,
    OpsCapability.MODEL_ROUTING,
    OpsCapability.EVAL,
    OpsCapability.GROUNDING,
    OpsCapability.TOKEN_LATENCY,
)

__all__ = [
    "CAPABILITIES",
    "DOMAIN",
    "BaselineManifest",
    "BaselineTaskDefinition",
    "BudgetLimit",
    "BudgetStatus",
    "EnforcementMode",
    "ModelAuthorityCeiling",
    "ModelCandidate",
    "ModelCandidatePolicy",
    "ModelCapabilityEvidence",
    "ModelContextRequirement",
    "ModelGovernancePolicy",
    "ModelInvocationEvidence",
    "ModelRoutingCapability",
    "ModelSelectionDecision",
    "ModelSelectionGateway",
    "ModelSelectionOutcome",
    "ModelSelectionRequest",
    "ModelTier",
    "ModelUsageLedger",
    "ModelUsageRecord",
    "PricingSource",
    "ProviderRoutingStatus",
    "ReasoningEffort",
    "SelectionResourceBudget",
    "StructuredOutputRequirement",
    "TaskClass",
    "TaskCriticality",
    "TaskRoutingProfile",
    "TokenAccountingSource",
    "default_model_usage_path",
    "load_baseline_manifest",
    "load_model_governance_policy",
    "route_model_selection_request",
    "select_model_candidate",
    "unavailable_usage_record",
]
